<?php

/**
 * @file
 * Defines hook implementations for the Matthew guestbook module.
 */

/**
 * Implements hook_theme().
 */
function matthew_guestbook_theme(array $existing, string $type, string $theme, string $path): array {
  $extensionPathResolver = Drupal::service('extension.path.resolver');
  return [
    'guestbook-entries' => [
      'variables' => [
        'entries' => [],
      ],
      'template' => 'guestbook-entries',
      'path' => $extensionPathResolver->getPath('module', 'matthew_guestbook') . '/templates',
    ],
  ];
}
